<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="PatientAppt.aspx.cs" Inherits="Hospital_System.Patient.PatientAppt" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            font-size: x-large;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>
        <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="~/Patient/patientHome.aspx">Patient Home</asp:HyperLink>
    </p>
    <h2 class="auto-style1">
        <strong>Your appointments:</strong></h2>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" Height="215px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="564px">
            <AlternatingRowStyle BackColor="White" />
            <FooterStyle BackColor="#CCCC99" />
            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#F7F7DE" />
            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FBFBF2" />
            <SortedAscendingHeaderStyle BackColor="#848384" />
            <SortedDescendingCellStyle BackColor="#EAEAD3" />
            <SortedDescendingHeaderStyle BackColor="#575357" />
        </asp:GridView>
    </p>
    <h2>
        Create Appointments:</h2>
    <p>
        Select Department:
        <asp:DropDownList ID="DropDownList_Department" runat="server" AutoPostBack="True" Height="16px" OnSelectedIndexChanged="DropDownList_Department_SelectedIndexChanged" Width="160px">
            <asp:ListItem>Family Care</asp:ListItem>
            <asp:ListItem>ICU</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        Select a Doctor:
        <asp:DropDownList ID="DropDownList_doctor" runat="server" Width="174px">
        </asp:DropDownList>
    </p>
    <p>
        Select Date For appointment:
        <asp:Calendar ID="Calendar1" runat="server"></asp:Calendar>
    </p>
    <p>
        Select Time:
        <asp:TextBox ID="TextBox_time" runat="server" TextMode="Time"></asp:TextBox>
    </p>
    <p>
        What is the Purpose of the Appointment:
    </p>
    <p>
        <asp:TextBox ID="TextBox_purpose" runat="server" Height="78px" TextMode="MultiLine" Width="349px"></asp:TextBox>
    </p>
    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Create Appointment" />
    <p>
    </p>
</asp:Content>
